### PR TITLE
support for socket.io v1.4.8

### PR DESCRIPTION
**Pull request by MasahiroMorita**
I have modified socket.io-ruby-emitter to support the latest socket.io v1.4.8.
please check it. thanks.

### CODE REVIEW

**Comment by achwedyk** [comment]
That doesn't seem to work for me using Socket.IO v1.4.8 and Redis server v3.2.1.
Which version of Redis server was used to test it?

**Comment by MasahiroMorita** [comment]
I use:
* ruby 1.9.3
* rails 3.2.12
* redis 2.8.4

travis-ci reported that the test passed on ruby 2.0, but failed on ruby 2.1 and 2.2.
I'm not sure the reasons, but it seems that some error is occurred during bundle install.

**Comment by achwedyk** [comment]
Right, I've tested using Ruby 2.1.4 and Redis v3.2.1. That might be the reason.

**Comment by nulltask** [comment]
@MasahiroMorita I'd like to help you. Please check out following issues.

* travis-ci/travis-ci#5239
* bundler/bundler#3558

Please try to update `.travis.yml`.

**Comment by MasahiroMorita** [comment]
thanks! @nulltask 
I try this.

**Comment by nulltask** [comment]
I've just merged and published as 1.0.0 to rubygems. thanks.

**Pull request merged**
